import { useState, useEffect, useRef } from "react";
import { C, getAnthropicKey, todayStr } from "../constants";
import { sbRest } from "../lib/supabase";
import { Badge, Card, Btn, Section, chipBtn, inputStyle } from "./UI";

const cpyBtn = { fontSize: 10, color: C.teal, background: `${C.teal}15`, border: `1px solid ${C.teal}33`, borderRadius: 8, padding: "3px 10px", cursor: "pointer", fontFamily: "inherit" };
const SAMPLE_QUESTIONS = ["自己PRをしてください","学生時代に力を入れたことを教えてください","志望動機を教えてください","あなたの強みと弱みを教えてください","チームで取り組んだ経験を教えてください","挫折経験とそこから学んだことを教えてください","入社後にやりたいことを教えてください","他にはどんな企業を受けていますか？"];

export default function InterviewLabView({ addLog, userId }) {
  const [phase, setPhase] = useState("select");
  const [question, setQuestion] = useState("");
  const [customQ, setCustomQ] = useState("");
  const [transcript, setTranscript] = useState("");
  const [recordingSec, setRecordingSec] = useState(0);
  const [firstWordSec, setFirstWordSec] = useState(null);
  const [memo, setMemo] = useState("");
  const [logs, setLogs] = useState([]);
  const [logsLoaded, setLogsLoaded] = useState(false);
  const [showLogs, setShowLogs] = useState(false);
  const [transcribing, setTranscribing] = useState(false);
  const [transcribeError, setTranscribeError] = useState("");
  const [aiAnalysis, setAiAnalysis] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [showRevision, setShowRevision] = useState(false);
  const [apiKey, setApiKey] = useState(() => { try { return localStorage.getItem("compass_openai_key") || ""; } catch { return ""; } });
  const [showKeyInput, setShowKeyInput] = useState(false);
  const [keyDraft, setKeyDraft] = useState("");
  const saveApiKey = (k) => { setApiKey(k); try { localStorage.setItem("compass_openai_key", k); } catch {} setShowKeyInput(false); };
  const mediaRecorderRef = useRef(null); const audioChunksRef = useRef([]); const timerRef = useRef(null); const firstWordRef = useRef(null); const streamRef = useRef(null);

  useEffect(() => { sbRest("GET","interview_logs?order=created_at.desc").then((rows)=>{if(rows) setLogs(rows);}).catch(()=>{ try { setLogs(JSON.parse(localStorage.getItem("compass_interview_logs")||"[]")); } catch {} }).finally(()=>setLogsLoaded(true)); }, []);

  const saveLog = async (entry) => { try { const uid = userId; const row = await sbRest("POST","interview_logs",{user_id:uid,date:entry.date,question:entry.question,duration:entry.duration,first_word:entry.firstWord,transcript:entry.transcript,memo:entry.memo}); setLogs((p)=>[row[0]||entry,...p]); } catch { setLogs((p)=>[entry,...p]); try { localStorage.setItem("compass_interview_logs",JSON.stringify([entry,...logs])); } catch {} } };

  const startRecording = async () => { const q = customQ.trim()||question; if (!q) return; setTranscript(""); setFirstWordSec(null); setRecordingSec(0); setTranscribeError(""); setAiAnalysis(null); firstWordRef.current = null; audioChunksRef.current = [];
    try { const stream = await navigator.mediaDevices.getUserMedia({audio:true}); streamRef.current = stream; const t0 = Date.now(); setPhase("recording"); timerRef.current = setInterval(()=>setRecordingSec(Math.floor((Date.now()-t0)/1000)),200);
      const SR = window.SpeechRecognition||window.webkitSpeechRecognition; if (SR) { const recog = new SR(); recog.lang="ja-JP"; recog.continuous=true; recog.interimResults=true; recog.onresult=(e)=>{ let ft="",it=""; for(let i=0;i<e.results.length;i++){if(e.results[i].isFinal) ft+=e.results[i][0].transcript; else it+=e.results[i][0].transcript;} const combined=ft+it; setTranscript(combined); if(combined.length>0&&firstWordRef.current===null){firstWordRef.current=Math.floor((Date.now()-t0)/1000);setFirstWordSec(firstWordRef.current);} }; recog.onerror=()=>{}; recog.start(); mediaRecorderRef._recog=recog; }
      const mimeType = MediaRecorder.isTypeSupported("audio/webm")?"audio/webm":MediaRecorder.isTypeSupported("audio/mp4")?"audio/mp4":"audio/ogg"; const mr = new MediaRecorder(stream,{mimeType}); mr.ondataavailable=(e)=>{if(e.data.size>0) audioChunksRef.current.push(e.data);}; mr.start(1000); mediaRecorderRef.current=mr;
    } catch { setTranscribeError("マイクへのアクセスが許可されていません。"); }
  };

  const stopRecording = () => { clearInterval(timerRef.current); if(mediaRecorderRef._recog){try{mediaRecorderRef._recog.stop();}catch{} mediaRecorderRef._recog=null;} if(mediaRecorderRef.current&&mediaRecorderRef.current.state!=="inactive") mediaRecorderRef.current.stop(); if(streamRef.current){streamRef.current.getTracks().forEach((t)=>t.stop());streamRef.current=null;} if(firstWordRef.current!==null) setFirstWordSec(firstWordRef.current); setPhase("transcribing"); setTimeout(()=>transcribeWithWhisper(),500); };

  const transcribeWithWhisper = async () => { setTranscribing(true); const chunks=audioChunksRef.current; if(!apiKey||chunks.length===0){setTranscribing(false);setPhase("result");return;} try { const mimeType=chunks[0]?.type||"audio/webm"; const ext=mimeType.includes("mp4")?"mp4":mimeType.includes("ogg")?"ogg":"webm"; const blob=new Blob(chunks,{type:mimeType}); const formData=new FormData(); formData.append("file",blob,`recording.${ext}`); formData.append("model","whisper-1"); formData.append("language","ja"); const res=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`},body:formData}); if(!res.ok){const err=await res.json();throw new Error(err.error?.message||"Whisper APIエラー");} const data=await res.json(); if(data.text) setTranscript(data.text); } catch(e){setTranscribeError(`Whisper失敗: ${e.message}（Web Speechの結果を使用）`);} finally{setTranscribing(false);setPhase("result");} };

  const saveResult = async () => { const q=customQ.trim()||question; const entry={date:new Date().toLocaleDateString("ja-JP"),question:q,duration:recordingSec,firstWord:firstWordSec,transcript,memo}; await saveLog(entry); if(addLog) addLog({date:todayStr(),content:`面接練習：${q.slice(0,20)}`,minutes:Math.ceil(recordingSec/60)||1,points:1}); setPhase("saved"); };

  const analyzeWithAI = async () => { const key=getAnthropicKey(); if(!key){alert("StudyタブでClaude APIキーを設定してください");return;} if(!transcript?.trim()){alert("文字起こし結果がありません");return;} setAnalyzing(true);setAiAnalysis(null);setShowRevision(false); const q=customQ.trim()||question; const cpm=recordingSec>0?Math.round((transcript.length/recordingSec)*60):0; const sj=cpm>400?"速すぎ":cpm<200?"やや遅い":"適切なペース";
    try { const prompt=`就活面接コーチとして以下の回答を分析。\n【質問】${q}【時間】${recordingSec}秒【速度】${cpm}字/分（${sj}）\n【文字起こし】${transcript}\nJSONで返してください：\n{"speed_comment":"速度評価","density":"密度評価","structure":"PREP等の構造評価","depth":"内容の深さ","expression":"表現の改善点","next_action":"最優先改善点1つ","revision":"【参考案】改善例"}`; const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model:"claude-haiku-4-5-20251001",max_tokens:2500,messages:[{role:"user",content:prompt}]})}); const data=await res.json(); setAiAnalysis(JSON.parse((data.content?.[0]?.text||"").replace(/```json|```/g,"").trim())); } catch(e){setAiAnalysis({error:"分析に失敗: "+e.message});} finally{setAnalyzing(false);} };

  const resetAll = () => { setPhase("select");setQuestion("");setCustomQ("");setTranscript("");setRecordingSec(0);setFirstWordSec(null);setMemo("");setTranscribeError("");setAiAnalysis(null);setShowRevision(false); };
  const fmtSec = (s) => { if(s===null||s===undefined) return "—"; return `${Math.floor(s/60)}分${s%60}秒`; };

  const ApiKeyCard = () => (<Card style={{marginBottom:16,border:`1px solid ${apiKey?C.teal+"44":C.yellow+"44"}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:12,fontWeight:700,color:apiKey?C.teal:C.yellow}}>{apiKey?"✓ Whisper API 有効":"⚠ OpenAI APIキー未設定"}</div><div style={{fontSize:11,color:C.faint,marginTop:2}}>{apiKey?"高精度な文字起こしが使えます":"設定すると精度が大幅向上します"}</div></div><button onClick={()=>{setKeyDraft(apiKey);setShowKeyInput(!showKeyInput);}} style={{background:"none",border:`1px solid ${C.cardBorder}`,color:C.sub,borderRadius:8,padding:"6px 12px",fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>{showKeyInput?"閉じる":apiKey?"変更":"設定"}</button></div>{showKeyInput&&(<div style={{marginTop:12}}><input style={{...inputStyle,marginBottom:8,fontFamily:"monospace",fontSize:12}} type="password" value={keyDraft} onChange={(e)=>setKeyDraft(e.target.value)} placeholder="sk-proj-..."/><div style={{fontSize:11,color:C.faint,marginBottom:8}}>このデバイスのみに保存されます</div><div style={{display:"flex",gap:8}}>{apiKey&&<Btn variant="ghost" onClick={()=>{saveApiKey("");setKeyDraft("");}} style={{flex:1,fontSize:12}}>削除</Btn>}<Btn onClick={()=>saveApiKey(keyDraft.trim())} style={{flex:2,fontSize:12}}>保存</Btn></div></div>)}</Card>);

  if (phase==="select") return (<div><Section kicker="改善に集中する練習" title="Interview Lab"/><p style={{fontSize:13,color:C.sub,marginTop:-10,marginBottom:16,lineHeight:1.6}}>録音→Whisper文字起こし→AI分析→改善メモ。練習1回で +1pt。</p><ApiKeyCard/><Card style={{marginBottom:16}}><div style={{fontSize:12,color:C.sub,marginBottom:10}}>質問を選ぶ</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{SAMPLE_QUESTIONS.map((q)=>(<button key={q} onClick={()=>{setQuestion(q);setCustomQ("");}} style={{...chipBtn(question===q,C.teal),textAlign:"left",padding:"10px 14px",borderRadius:10,whiteSpace:"normal",lineHeight:1.4}}>{q}</button>))}</div></Card><Card style={{marginBottom:16}}><div style={{fontSize:12,color:C.sub,marginBottom:8}}>または自由入力</div><textarea style={{...inputStyle,height:70,resize:"vertical"}} value={customQ} onChange={(e)=>{setCustomQ(e.target.value);setQuestion("");}} placeholder="例：なぜうちの会社を志望したのですか？"/></Card><Btn onClick={()=>{if(customQ.trim()||question) setPhase("ready");}} style={{width:"100%",opacity:(customQ.trim()||question)?1:0.4}}>準備できたら次へ →</Btn>
    {logs.length>0&&(<div style={{marginTop:24}}><button onClick={()=>setShowLogs(!showLogs)} style={{background:"none",border:"none",color:C.sub,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>{showLogs?"▼":"▶"} 練習ログ ({logs.length})</button>{showLogs&&(<div style={{marginTop:10,display:"flex",flexDirection:"column",gap:10}}>{logs.map((l)=>(<Card key={l.id||l.date} style={{padding:"12px 14px"}}><div style={{fontSize:11,color:C.faint,marginBottom:4}}>{l.date}</div><div style={{fontSize:13,fontWeight:700,marginBottom:6}}>{l.question}</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Badge color={C.teal}>⏱ {fmtSec(l.duration)}</Badge></div>{l.memo&&<div style={{fontSize:12,color:C.sub,marginTop:6}}>💬 {l.memo}</div>}</Card>))}</div>)}</div>)}</div>);

  if (phase==="ready") { const q=customQ.trim()||question; return (<div><Section kicker="準備" title="録音開始"/><Card style={{marginBottom:20,border:`1px solid ${C.teal}44`}}><div style={{fontSize:12,color:C.teal,marginBottom:8}}>今回の質問</div><div style={{fontSize:16,fontWeight:700,lineHeight:1.5}}>{q}</div></Card><div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:14,padding:16,marginBottom:20,fontSize:13,color:C.sub,lineHeight:1.7}}>・録音ボタンを押してから答え始めましょう<br/>・ブラウザがマイクへのアクセスを求めたら「許可」してください<br/>・{apiKey?"停止後にWhisperが自動で文字起こしします":"停止後に音声認識の結果が表示されます"}</div><div style={{display:"flex",gap:10}}><Btn variant="ghost" onClick={()=>setPhase("select")} style={{flex:1}}>戻る</Btn><Btn onClick={startRecording} style={{flex:2,background:"linear-gradient(135deg, #FF6B6B, #d4504f)"}}>🎙️ 録音開始</Btn></div></div>); }

  if (phase==="recording") return (<div><Section kicker="録音中" title="回答してください"/><Card style={{marginBottom:16,border:`1px solid ${C.red}55`,textAlign:"center"}}><div style={{fontSize:48,marginBottom:8}}>🎙️</div><div style={{fontSize:28,fontWeight:900,color:C.red,fontVariantNumeric:"tabular-nums"}}>{fmtSec(recordingSec)}</div><div style={{fontSize:12,color:C.faint,marginTop:4}}>録音中…</div></Card><Card style={{marginBottom:16}}><div style={{fontSize:11,color:C.sub,marginBottom:8}}>リアルタイム（暫定）</div><div style={{fontSize:13,color:C.text,lineHeight:1.7,minHeight:60,whiteSpace:"pre-wrap"}}>{transcript||<span style={{color:C.faint}}>話すと文字が表示されます…</span>}</div>{apiKey&&<div style={{fontSize:11,color:C.faint,marginTop:8}}>停止後にWhisperで高精度変換されます</div>}</Card><Btn onClick={stopRecording} style={{width:"100%",background:"linear-gradient(135deg, #FF6B6B, #d4504f)"}}>⏹ 録音停止</Btn></div>);

  if (phase==="transcribing") return (<div><Section kicker="処理中" title="文字起こし中…"/><Card style={{textAlign:"center",padding:40}}><div style={{fontSize:40,marginBottom:16}}>🔄</div><div style={{fontSize:14,color:C.teal,fontWeight:700}}>Whisperが変換中です</div></Card></div>);

  if (phase==="result"||phase==="saved") { const q=customQ.trim()||question; const cpm=recordingSec>0?Math.round((transcript.length/recordingSec)*60):0; const speedColor=cpm>400?C.red:cpm<200?C.yellow:C.green;
    return (<div><Section kicker="分析結果" title="練習結果"/>{transcribeError&&<div style={{background:`${C.yellow}15`,border:`1px solid ${C.yellow}44`,borderRadius:10,padding:"10px 14px",fontSize:12,color:C.yellow,marginBottom:12}}>{transcribeError}</div>}
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:16}}>{[{label:"回答時間",val:fmtSec(recordingSec),color:C.teal},{label:"話し始めるまで",val:firstWordSec!==null?`${firstWordSec}秒`:"—",color:C.sub},{label:"話す速度",val:`${cpm}字/分`,color:speedColor},{label:"文字数",val:`${transcript.length}字`,color:C.sub}].map((s)=>(<Card key={s.label} style={{padding:14,textAlign:"center"}}><div style={{fontSize:20,fontWeight:900,color:s.color}}>{s.val}</div><div style={{fontSize:10,color:C.faint,marginTop:4}}>{s.label}</div></Card>))}</div>
      {transcript&&(<Card style={{marginBottom:16}}><div style={{fontSize:12,color:C.sub,marginBottom:8}}>文字起こし</div><div style={{fontSize:13,color:C.text,lineHeight:1.7,whiteSpace:"pre-wrap"}}>{transcript}</div></Card>)}
      {phase==="result"&&!aiAnalysis&&(<button onClick={analyzeWithAI} disabled={analyzing} style={{width:"100%",marginBottom:16,background:analyzing?"rgba(255,255,255,0.05)":`linear-gradient(135deg, ${C.purple}44, ${C.teal}44)`,border:`1px solid ${C.purple}55`,borderRadius:14,padding:"14px",cursor:analyzing?"default":"pointer",fontSize:14,fontWeight:700,color:analyzing?C.faint:C.text,fontFamily:"inherit"}}>{analyzing?"🤖 AIが分析中…":"🤖 AIに分析してもらう"}</button>)}
      {aiAnalysis&&!aiAnalysis.error&&(<div style={{marginBottom:16,display:"flex",flexDirection:"column",gap:8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:12,color:C.purple,fontWeight:700}}>🤖 AI分析結果</div><button onClick={()=>{const text=[["話す速度",aiAnalysis.speed_comment],["内容の密度",aiAnalysis.density],["構造・流れ",aiAnalysis.structure],["内容の深さ",aiAnalysis.depth],["表現",aiAnalysis.expression],["🎯 最優先改善点",aiAnalysis.next_action]].filter(([,v])=>v).map(([k,v])=>`【${k}】\n${v}`).join("\n\n");navigator.clipboard.writeText(text).catch(()=>{});}} style={{...cpyBtn}}>📋 全コピー</button></div>
        {[{label:"話す速度",value:aiAnalysis.speed_comment,color:speedColor},{label:"内容の密度",value:aiAnalysis.density,color:C.teal},{label:"構造・流れ",value:aiAnalysis.structure,color:C.purple},{label:"内容の深さ",value:aiAnalysis.depth,color:C.yellow},{label:"表現",value:aiAnalysis.expression,color:"#0ea5e9"}].map((item)=>item.value&&(<div key={item.label} style={{background:`${item.color}10`,border:`1px solid ${item.color}30`,borderRadius:10,padding:"8px 12px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><div style={{fontSize:10,color:item.color,fontWeight:700}}>{item.label}</div><button onClick={()=>navigator.clipboard.writeText(item.value).catch(()=>{})} style={{fontSize:9,color:C.faint,background:"none",border:"none",cursor:"pointer",padding:0}}>📋</button></div><div style={{fontSize:12,color:C.text,lineHeight:1.6}}>{item.value}</div></div>))}
        {aiAnalysis.next_action&&(<div style={{background:`${C.green}10`,border:`1px solid ${C.green}30`,borderRadius:10,padding:"8px 12px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><div style={{fontSize:10,color:C.green,fontWeight:700}}>🎯 最優先で改善すること</div><button onClick={()=>navigator.clipboard.writeText(aiAnalysis.next_action).catch(()=>{})} style={{fontSize:9,color:C.faint,background:"none",border:"none",cursor:"pointer",padding:0}}>📋</button></div><div style={{fontSize:12,color:C.text,lineHeight:1.6,fontWeight:600}}>{aiAnalysis.next_action}</div></div>)}
        {aiAnalysis.revision&&(<div><button onClick={()=>setShowRevision((p)=>!p)} style={{fontSize:11,color:C.yellow,background:`${C.yellow}15`,border:`1px solid ${C.yellow}33`,borderRadius:99,padding:"4px 12px",cursor:"pointer",fontFamily:"inherit"}}>{showRevision?"▼ 改善例を隠す":"▶ 改善例を見る（参考）"}</button>{showRevision&&(<div style={{marginTop:8,background:`${C.yellow}08`,border:`1px solid ${C.yellow}22`,borderRadius:10,padding:"10px 12px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:10,color:C.yellow}}>※ あくまで参考案。</div><button onClick={()=>navigator.clipboard.writeText(aiAnalysis.revision).catch(()=>{})} style={{fontSize:10,color:C.yellow,background:`${C.yellow}15`,border:`1px solid ${C.yellow}33`,borderRadius:8,padding:"2px 8px",cursor:"pointer",fontFamily:"inherit"}}>📋</button></div><div style={{fontSize:12,color:C.text,lineHeight:1.8,whiteSpace:"pre-wrap"}}>{aiAnalysis.revision}</div></div>)}</div>)}
      </div>)}
      {aiAnalysis?.error&&<div style={{fontSize:12,color:C.red,marginBottom:16}}>{aiAnalysis.error}</div>}
      {phase==="result"&&(<Card style={{marginBottom:16}}><div style={{fontSize:12,color:C.sub,marginBottom:8}}>改善メモ（任意）</div><textarea style={{...inputStyle,height:80,resize:"vertical"}} value={memo} onChange={(e)=>setMemo(e.target.value)} placeholder="次回への改善点など自由に"/></Card>)}
      {phase==="saved"&&(<Card style={{marginBottom:16,border:`1px solid ${C.green}44`,background:`${C.green}08`}}><div style={{fontSize:15,fontWeight:700,color:C.green}}>🎉 保存しました！ +1pt 獲得</div></Card>)}
      <div style={{display:"flex",gap:10}}><Btn variant="ghost" onClick={resetAll} style={{flex:1}}>最初から</Btn>{phase==="result"&&<Btn onClick={saveResult} style={{flex:2}}>💾 保存 (+1pt)</Btn>}</div>
    </div>);
  }
  return null;
}
